### PR TITLE
Automate Installation with Ducky Scripts: Top 300 Most Popular Software Chocolatey Packages

### PR DESCRIPTION
**Pull request by ooovenenoso**
These scripts are designed to automate the installation process for various programs using the Chocolatey package manager on Windows computers. The scripts utilize Ducky Script language and are intended for use with USB Rubber Ducky/Flipper Zero devices or other Ducky Script compatible devices.

### CODE REVIEW

**Comment by ooovenenoso** [comment]
**Subject:** Report of Inappropriate Behavior in the Repository

**Hello Admin Team,**

I hope you are well. I'd like to report an unpleasant situation I experienced in the repository. Recently, I submitted a review request and had an interaction with another user that was quite negative and unprofessional.

In my opinion, the tone used and the condescending attitude are inappropriate and do not foster a collaborative environment. As a member of the community and a contributor, I feel uncomfortable and demotivated by this type of interaction.

My intention in submitting my pull request was to contribute positively and engage in the development process in a constructive manner. However, this experience has been disheartening and has led me to reconsider my interest in continuing to contribute to the repository.

I appreciate the time and effort that all of you dedicate to keeping the repository running. I hope that steps will be taken to address this kind of behavior, as it can have a negative impact on other community members.

Thank you for your attention to this matter. I am available for any comments or necessary follow-up.

Sincerely,
ooovenenoso!

**Comment by ooovenenoso** [comment]
**Comment:**
Hello everyone,

I wanted to let you all know that I've decided to publish the pull request under the name "Choco-Ducky" on my profile. This decision comes as a result of the experiences I've encountered recently. Despite the challenges and interactions faced, I believe in the importance of sharing and collaborating on projects that can benefit the community.

While there have been some hurdles along the way, I'm hopeful that this repository will continue to evolve and contribute positively to those who are interested in using Ducky Scripts for Chocolatey automation. It's my hope that this step will allow for smoother collaboration and communication without the unnecessary disruptions.

Thank you to those who have provided support and encouragement. Let's continue working together to create meaningful contributions.

Best regards,
ooovenenoso

Note:
Potential pedantic behavior on the discord server linked to this repo.

**Comment by UNC0V3R3D** [comment]
Don't you ever make random advertisements in here again. Good luck with finding another repo, don't need such a bold person.

**Comment by ooovenenoso** [comment]
@UNC0V3R3D I observed that my previous comment was so groundbreaking that it had to be vanished from the discussion. But let's bypass trivialities; what truly disheartens me is the nonchalance toward pull request reviews and the undeniable condescending attitude that seems to be the de facto tone here.

As we flood ourselves with poorly synchronized support servers, we forget the most elementary norms of courtesy and communication. In this light, I confess that my respect for the project is in rapid decline.

Given that we are on GitHub's platform, it's timely to remind ourselves of specific policies such as the 'Acceptable Use Policy' and the 'Contributor Code of Conduct'. These are not optional accessories; they are the bedrock that ensures a collaborative and respectful environment.

If my forthrightness is misconstrued as audacity, so be it. At the end of the day, my sole interest is in catalyzing improvements where they are most needed.

Perhaps it's time to deflate some of the grandiose air that seems to flood these virtual corridors, before other contributors join my viewpoint.

If this comment also turns out to be too 'bold' for your taste, feel free to make it disappear; it seems to be the trend.

Best regards,
ooovenenoso

**Comment by UNC0V3R3D** [comment]
Writing your text using ChatGPT also doesn't make it better...

**Pull request closed without merging**
